// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SensorToUserBinding SensorToUserBinding
//
// Связка датчика с пользователем
// Example: {"sensor_id":1}
//
// swagger:model SensorToUserBinding
type SensorToUserBinding struct {

	// Идентификатор датчика
	// Required: true
	// Minimum: 1
	SensorID *int64 `json:"sensor_id"`
}

// Validate validates this sensor to user binding
func (m *SensorToUserBinding) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSensorID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SensorToUserBinding) validateSensorID(formats strfmt.Registry) error {

	if err := validate.Required("sensor_id", "body", m.SensorID); err != nil {
		return err
	}

	if err := validate.MinimumInt("sensor_id", "body", *m.SensorID, 1, false); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this sensor to user binding based on context it is used
func (m *SensorToUserBinding) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SensorToUserBinding) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SensorToUserBinding) UnmarshalBinary(b []byte) error {
	var res SensorToUserBinding
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
