// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SensorEvent SensorEvent
//
// Событие датчика
// Example: {"payload":10,"sensor_serial_number":"1234567890"}
//
// swagger:model SensorEvent
type SensorEvent struct {

	// Информация от датчика
	// Required: true
	Payload *int64 `json:"payload"`

	// Серийный номер датчика
	// Required: true
	// Pattern: ^\d{10}$
	SensorSerialNumber *string `json:"sensor_serial_number"`
}

// Validate validates this sensor event
func (m *SensorEvent) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePayload(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSensorSerialNumber(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SensorEvent) validatePayload(formats strfmt.Registry) error {

	if err := validate.Required("payload", "body", m.Payload); err != nil {
		return err
	}

	return nil
}

func (m *SensorEvent) validateSensorSerialNumber(formats strfmt.Registry) error {

	if err := validate.Required("sensor_serial_number", "body", m.SensorSerialNumber); err != nil {
		return err
	}

	if err := validate.Pattern("sensor_serial_number", "body", *m.SensorSerialNumber, `^\d{10}$`); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this sensor event based on context it is used
func (m *SensorEvent) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SensorEvent) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SensorEvent) UnmarshalBinary(b []byte) error {
	var res SensorEvent
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
